---

- hosts: backup
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:

    - name: Montar partição 
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/diario/prod-devops/{{ item }}
        path: /mnt/origem-{{ item }}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - nexus
        - git

    - name: Montar partição
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/diario/prod-devops/{{ item }}
        path: /mnt/destino-{{ item }}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - nexus
        - git

    - name: Copiando arquivos
      copy:
        src: /mnt/origem-git/
        dest: /mnt/destino-git/
        remote_src: true

    - name: Copiando arquivos
      copy:
        src: /mnt/origem-nexus/
        dest: /mnt/destino-nexus/
        remote_src: true

      mount:
        path: /mnt/{{ item }}
        state: absent
      become: true
      loop:
        - /mnt/origem-git/
        - /mnt/origem-nexus/
        - /mnt/destino-git/
        - /mnt/destino-nexus/
