- hosts: backup
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: Montar partição INTRA
      mount:
        src: "{{ item.src }}"
        path: "/mnt/{{ item.dst }}"
        opts: ro
        fstype: nfs
        state: ephemeral
      loop:
        - { src: "10.6.45.202:/backup/iris3/backup_gitlab", dst: "git-origem" }
        - { src: "10.6.45.202:/backup/iris3/backup_nexus", dst: "nexus-origem" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/git/seg", dst: "git-seg" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/git/ter", dst: "git-ter" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/git/qua", dst: "git-qua" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/git/qui", dst: "git-qui" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/git/sex", dst: "git-sex" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/git/sab", dst: "git-sab" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/git/dom", dst: "git-dom" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/nexus/seg", dst: "nexus-seg" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/nexus/ter", dst: "nexus-ter" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/nexus/qua", dst: "nexus-qua" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/nexus/qui", dst: "nexus-qui" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/nexus/sex", dst: "nexus-sex" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/nexus/sab", dst: "nexus-sab" }
        - { src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/nexus/dom", dst: "nexus-dom" }

    - name: Copiando arquivos
      copy:
        src: "/mnt/git-origem/"
        dest: "/mnt/{{ item }}/"
        remote_src: true
      loop:
        - "git-seg"
        - "git-ter"
        - "git-qua"
        - "git-qui"
        - "git-sex"
        - "git-sab"
        - "git-dom"

    - name: Copiando arquivos
      copy:
        src: "/mnt/nexus-origem/"
        dest: "/mnt/{{ item }}/"
        remote_src: true
      loop:
        - "nexus-seg"
        - "nexus-ter"
        - "nexus-qua"
        - "nexus-qui"
        - "nexus-sex"
        - "nexus-sab"
        - "nexus-dom"

    - name: Removendo montagem
      mount:
        path: "/mnt/{{ item }}/"
        state: absent
      loop:
        - git-origem
        - nexus-origem
        - git-seg
        - git-ter
        - git-qua
        - git-qui
        - git-sex
        - git-sab
        - git-dom
        - nexus-seg
        - nexus-ter
        - nexus-qua
        - nexus-qui
        - nexus-sex
        - nexus-sab
        - nexus-dom