---

- hosts: backup
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: Montar partição
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/{{ item }}/dom
        path: /mnt/origem-{{ item }}
        opts: ro
        fstype: nfs
        state: ephemeral
      loop:
        - nexus
        - git

    - name: Montar partição
      mount:
        src: nas3.dpe-go.intra:/SEMANAL/prod-devops/{{ item }}/dom
        path: /mnt/destino-{{ item }}
        opts: ro
        fstype: nfs
        state: ephemeral
      loop:
        - nexus
        - git

    - name: Executar diff
      command: diff /mnt/origem-nexus/ /mnt/destino-nexus/
      register: diff_result_nexus
      ignore_errors: true

    - name: Executar diff
      command: diff /mnt/origem-git/ /mnt/destino-git/
      register: diff_result_git
      ignore_errors: true

    - name: Copiando arquivos
      copy:
        src: /mnt/origem-git/
        dest: /mnt/destino-git/
      when: diff_result_git.stdout != ""

    - name: Copiando arquivos
      copy:
        src: /mnt/origem-nexus/
        dest: /mnt/destino-nexus/
      when: diff_result_nexus.stdout != ""

      mount:
        path: /mnt/{{ item.dst }}
        state: unmounted
      loop:
        - /mnt/origem-git/
        - /mnt/origem-nexus/
        - /mnt/destino-git/
        - /mnt/destino-nexus/
