# ###################################
# Backup dos Arquivos  Dirario      #
# ###################################


# Objetivo: Copiar todos os arquivos da diretorio SRV_PERSEFONE3_STI que está no storage 10.6.45.202 para o nas3.dpe-go.intra. Ponto de antecção,
# Sempre comprar o di seguinte com o dia anterior, ou seja, se teve alteração nos arquivos de segunda para terça então copiar se não tem mantém.

# Passos do Playbook


# 1) Montar - 10.6.45.202- /backup2/FILESERVER/SRV_PERSEFONE3_STI/SRV_PERSEFONE3_STI
# 2) Montar - nas3.dpe-go.intra - /mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/{Seg-Sab}
# 3) Copiar arquivos comparando, exemplo diff - (Origem - 10.6.45.202) para Destino (Destino - nas3.dpe-go.intra)
# 4) Desmontar origem (Origem - 10.6.45.202) e Destino ( Destino - nas3.dpe-go.intra)



# 10.6.45.202:/backup2/FILESERVER/SRV_PERSEFONE3_STI/SRV_PERSEFONE3_STI       nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/seg
#                                                                             nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/ter
#                                                                             nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/qua
#                                                                             nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/qui
#                                                                             nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/sex
#                                                                             nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/sab
#                                                                             nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/dom 

- name: Realizar backup diferencial diário
  hosts: backup
  gather_facts: false
  vars:
    origem: "/backup2/FILESERVER/SRV_PERSEFONE3_STI/SRV_PERSEFONE3_STI"
    destinos:
      - "/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/seg"
      - "/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/ter"
      - "/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/qua"
      - "/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/qui"
      - "/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/sex"
      - "/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/sab"
  tasks:
    - name: Montar origem
      mount:
        src: "10.6.45.202:/backup2/FILESERVER/SRV_PERSEFONE3_STI/SRV_PERSEFONE3_STI"
        path: "{{ origem }}"
        fstype: nfs
        state: mounted

    - name: Montar destinos
      mount:
        src: "nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/arquivos/diferencial/{{ item }}"
        path: "{{ item }}"
        fstype: nfs
        state: mounted
      loop: "{{ destinos }}"

    - name: Realizar cópia dos arquivos
      command: rsync -a --delete --link-dest="{{ origem }}/" "{{ origem }}/" "{{ item }}/"
      loop: "{{ destinos }}"