---

- hosts: backup
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  become: true
  tasks:
    ################################################################################## Realiza a montagem
    - name: Montar partição INTRA - Sabado
      mount:
        src: 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - { src: 'INTRA/6', dst: 'INTRA/6' }
        - { src: 'BATCH/6', dst: 'BATCH/6' }
        - { src: 'SPCONTAS/6', dst: 'SPCONTAS/6' }
    ################################################################################## Realiza a montagem

    ################################################################################## Realiza a montagem
    - name: Montar partição INTRA - Sabado
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - { src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra' }
        - { src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch' }
        - { src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas' }
    ################################################################################## Realiza a montagem
    
    ################################################################################## Realiza a copia dos arquivos
    - name: Pegando último arquivo da pasta INTRA
      shell: ls -t /mnt/INTRA/1/ | head -1
      become: true
      register: arquivo_atual_intra

    - name: Pegando último arquivo da pasta BATCH
      shell: ls -t /mnt/BATCH/1/ | head -1
      become: true
      register: arquivo_atual_batch

    - name: Pegando último arquivo da pasta SPCONTAS
      shell: ls -t/mnt/SPCONTAS/1/ | head -1
      become: true
      register: arquivo_atual_spcontas

    - name: Copiando arquivos INTRA
      copy:
        src: /mnt/INTRA/6/{{ arquivo_atual_intra.stdout }}
        dest: "/mnt/prod-intra/bd/intra"
      become: true

    - name: Copiando arquivos INTRA
      copy:
        src: /mnt/BATCH/6/{{ arquivo_atual_batch.stdout }}
        dest: "/mnt/prod-intra/bd/batch"
      become: true

    - name: Copiando arquivos
      copy:
        src: /mnt/SPCONTAS/6/{{ arquivo_atual_spcontas.stdout }}
        dest: "/mnt/prod-intra/bd/spcontas"
      become: true
    ################################################################################## Realiza a copia dos arquivos

    ################################################################################## Realiza a remoção do arquivo mais antigo da pasta
    - shell: ls -t /mnt/prod-intra/bd/intra/ | tail -1
      register: ultimo_arquivo_intra

    - shell: ls -t /mnt/prod-intra/bd/batch/ | tail -1
      register: ultimo_arquivo_batch
    
    - shell: ls -t /mnt/prod-intra/bd/spcontas/ | tail -1
      register: ultimo_arquivo_spcontas

    - name: Remove file (delete file)
      file:
        path: /mnt/prod-intra/bd/intra/{{ ultimo_arquivo_intra }}
        state: absent
      become: true

    - name: Remove file (delete file)
      file:
        path: /mnt/prod-intra/bd/batch/{{ ultimo_arquivo_batch }}
        state: absent
      become: true

    - name: Remove file (delete file)
      file:
        path: /mnt/prod-intra/bd/spcontas/{{ ultimo_arquivo_spcontas }}
        state: absent
      become: true
    ################################################################################## Realiza a remoção do arquivo mais antigo da pasta

    ################################################################################## Realiza a desmontagem
      mount:
        path: /mnt/{{ item.dst }}
        state: absent
      become: true
      loop:
        - { src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra' }
        - { src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch' }
        - { src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas' }
        - { src: 'INTRA/6', dst: 'INTRA/6' }
        - { src: 'BATCH/6', dst: 'BATCH/6' }
        - { src: 'SPCONTAS/6', dst: 'SPCONTAS/6' }
    ################################################################################## Realiza a desmontagem
