- hosts: 
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  become: true
  tasks:
    ################################################################################## Realiza a montagem
    - name: Montar partição INTRA - Segunda
      mount:
        src: 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - { src: 'INTRA/1', dst: 'INTRA/1' }
        - { src: 'BATCH/1', dst: 'BATCH/1' }
        - { src: 'SPCONTAS/1', dst: 'SPCONTAS/1' }
    ################################################################################## Realiza a montagem

    ################################################################################## Realiza a montagem
    - name: Montar partição INTRA - Segunda
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - { src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra' }
        - { src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch' }
        - { src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas' }
    ################################################################################## Realiza a montagem
    
    ################################################################################## Realiza a copia dos arquivos
    - name: Copiando arquivos
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
      become: true
      loop:
        - { src: '/mnt/INTRA/1/*-191001.tar.gz', dst: '/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra/' }
        - { src: '/mnt/BATCH/1/*-190002.tar.gz', dst: '/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch/' }
      
    - name: Pegando último arquivo da pasta SPCONTAS
      shell: ls -t /mnt/SPCONTAS/1/' | head -1
      become: true
      register: arquivo_atual

    - name: Copiando arquivos
      copy:
        src: /mnt/SPCONTAS/1/{{ arquivo_atual.stdout }}
        dest: "/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas/"
      become: true
    ################################################################################## Realiza a copia dos arquivos

    ################################################################################## Realiza a desmontagem
      mount:
        path: /mnt/{{ item.dst }}
        state: absent
      become: true
      loop:
        - { src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra' }
        - { src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch' }
        - { src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas' }
        - { src: 'INTRA/1', dst: 'INTRA/1' }
        - { src: 'BATCH/1', dst: 'BATCH/1' }
        - { src: 'SPCONTAS/1', dst: 'SPCONTAS/1' }
    ################################################################################## Realiza a desmontagem