# ####################################################
# Backup dos Banco de dados Dirario  - Sempre ás 22h #
# ####################################################

# Objetivo: Transferir os backup do Storage 10.6.45.202 para o Storage nas3.dpe-go.intra. De segunda a Domingo. Ponto de atenção Quando for na outra segunda,
# o arquivo que seria 8 vai sobreescrever o arquivo 1 que seria da primeira segunda feira.


# Passos do Playbook

# 1) Montar - 10.6.45.202 - INTRA,BATCH,SPCONTAS 1-7
# 2) Montar - nas3.dpe-go.intra - intra,batch,spcontas 1-7
# 3) Copiar arquivos (Origem) 10.6.45.202 - INTRA,BATCH,SPCONTAS 1-7 para Destino (Destino) nas3.dpe-go.intra - intra,batch,spcontas 1-7
# 4) Desmontar origem (10.6.45.202 - INTRA,BATCH,SPCONTAS) e Destino (nas3.dpe-go.intra - intra,batch,spcontas) 1-7


# Storage --> 10.6.45.202    Sempre ás 22h                                                           Storage --> nas3.dpe-go.intra Sempre ás 22h  


# Segunda                                                                Segunda 
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/INTRA/1/*-191001.tar.g        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/BATCH/1/*-190002.tar.gz       nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/SPCONTAS/1/ls -t | head -1    nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas


# Terça                                                                  Terça
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/INTRA/2/*-191001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/BATCH/2/*-190001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/SPCONTAS/2/ls -t | head -1     nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas

# Quarta                                                                 Qaurta
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/INTRA/3/*-191001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/BATCH/3/*-190002.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/SPCONTAS/3/ls -t | head -1     nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas

# Quinta                                                                 Quinta
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/INTRA/4/*-191001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/BATCH/4/*-190001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/SPCONTAS/4/ls -t | head -1     nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas

# Sexta                                                                  Sexta
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/INTRA/5/*-191001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/BATCH/5/*-191001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/SPCONTAS/5/ls -t | head -1     nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas

# Sabado                                                                Sabado
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/INTRA/6/*-191001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/BATCH/6/*-190001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/SPCONTAS/6/ls -t | head -1     nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas

# Domingo                                                                Domingo
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/INTRA/7/*-191001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/BATCH/7/*-190001.tar.gz        nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch
# 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/SPCONTAS/7/ls -t | head -1     nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas

- hosts: backup
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  become: true
  tasks:
    ################################################################################## Realiza a montagem
    - name: Montar partição INTRA - Segunda
      mount:
        src: 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - { src: 'INTRA/1', dst: 'INTRA/1' }
        - { src: 'BATCH/1', dst: 'BATCH/1' }
        - { src: 'SPCONTAS/1', dst: 'SPCONTAS/1' }
    ################################################################################## Realiza a montagem

    ################################################################################## Realiza a montagem
    - name: Montar partição INTRA - Segunda
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - { src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra' }
        - { src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch' }
        - { src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas' }
    ################################################################################## Realiza a montagem
    
    ################################################################################## Realiza a copia dos arquivos
    - name: Pegando último arquivo da pasta INTRA
      shell: ls -t /mnt/INTRA/1/' | head -1
      become: true
      register: arquivo_atual_intra

    - name: Pegando último arquivo da pasta BATCH
      shell: ls -t /mnt/BATCH/1/' | head -1
      become: true
      register: arquivo_atual_batch

    - name: Pegando último arquivo da pasta SPCONTAS
      shell: ls -t /mnt/SPCONTAS/1/' | head -1
      become: true
      register: arquivo_atual_spcontas

    - name: Copiando arquivos INTRA
      copy:
        src: /mnt/INTRA/1/{{ arquivo_atual_intra.stdout }}
        dest: "/mnt/prod-intra/bd/intra"
      become: true

    - name: Copiando arquivos INTRA
      copy:
        src: /mnt/BATCH/1/{{ arquivo_atual_batch.stdout }}
        dest: "/mnt/prod-intra/bd/batch"
      become: true

    - name: Copiando arquivos
      copy:
        src: /mnt/SPCONTAS/1/{{ arquivo_atual_spcontas.stdout }}
        dest: "/mnt/prod-intra/bd/spcontas"
      become: truess
    ################################################################################## Realiza a copia dos arquivos

    ################################################################################## Realiza a remoção do arquivo mais antigo da pasta
    - shell: ls -t /mnt/prod-intra/bd/intra/ | tail -1
      register: ultimo_arquivo_intra

    - shell: ls -t /mnt/prod-intra/bd/batch/ | tail -1
      register: ultimo_arquivo_batch
    
    - shell: ls -t /mnt/prod-intra/bd/spcontas/ | tail -1
      register: ultimo_arquivo_spcontas

    - name: Remove file (delete file)
      file:
        path: /mnt/prod-intra/bd/intra/{{ ultimo_arquivo_intra }}
        state: absent
      become: true

    - name: Remove file (delete file)
      file:
        path: /mnt/prod-intra/bd/batch/{{ ultimo_arquivo_batch }}
        state: absent
      become: true

    - name: Remove file (delete file)
      file:
        path: /mnt/prod-intra/bd/spcontas/{{ ultimo_arquivo_spcontas }}
        state: absent
      become: true
    ################################################################################## Realiza a remoção do arquivo mais antigo da pasta

    ################################################################################## Realiza a desmontagem
      mount:
        path: /mnt/{{ item.dst }}
        state: absent
      become: true
      loop:
        - { src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra' }
        - { src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch' }
        - { src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas' }
        - { src: 'INTRA/1', dst: 'INTRA/1' }
        - { src: 'BATCH/1', dst: 'BATCH/1' }
        - { src: 'SPCONTAS/1', dst: 'SPCONTAS/1' }
    ################################################################################## Realiza a desmontagem
