# #####################################################
# Backup Banco de dados Semanal  -  Sempre ás 22h     #
# #####################################################

# Objetivo: copiar sempre o ultimo arquivo(7=Domingo), nesse caso sempre aos Domingo ás 22h. Atenção sempre mantém 7 dias e depois sobreescrever no 8 dia.

# Passos do Playbook

# 1) Montar - nas3.dpe-go.intra - INTRA,BATCH,SPCONTAS
# 2) Montar - nas3.dpe-go.intra - intra,batch,spcontas
# 3) Copiar o arquivo mais atual de Domingo pasta 7 - (Origem Diario) nas3.dpe-go.intra - INTRA,BATCH,SPCONTAS para Destino (Destino Semanal) nas3.dpe-go.intra - intra,batch,spcontas
# 4) Desmontar origem (nas3.dpe-go.intra - INTRA,BATCH,SPCONTAS) e Destino (nas3.dpe-go.intra - intra,batch,spcontas)


# nas3.dpe-go.intra:mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra               nas3.dpe-go.intra:mnt/STG7A_UDMARISTA/NAS3/MENSAL/prod-intra/bd/intra          
# nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch              nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/MENSAL/prod-intra/bd/batch
# nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas           nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/MENSAL/prod-intra/bd/spcontas

- hosts: 
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  become: true
  tasks:
    ################################################################################## Realiza a montagem
    - name: Montar partição INTRA - Domingo
      mount:
        src: 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - { src: 'INTRA/7', dst: 'INTRA/7' }
        - { src: 'BATCH/7', dst: 'BATCH/7' }
        - { src: 'SPCONTAS/7', dst: 'SPCONTAS/7' }
    ################################################################################## Realiza a montagem

    ################################################################################## Realiza a montagem
    - name: Montar partição INTRA - Domingo
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - { src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra' }
        - { src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch' }
        - { src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas' }
    ################################################################################## Realiza a montagem
    
    ################################################################################## Realiza a copia dos arquivos
    - name: Copiando arquivos
      copy:
        src:
        dest:
      become: true
      loop:
        - { src: '/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/INTRA/7/*', dst: '/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra/' }
        - { src: '/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/BATCH/7/*', dst: '/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch/' }
        - { src: '/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/SPCONTAS/7/*', dst: '/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas/' }
    ################################################################################## Realiza a copia dos arquivos

    ################################################################################## Realiza a desmontagem
      mount:
        path: /mnt/{{ item.dst }}
        state: absent
      become: true
      loop:
        - { src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra' }
        - { src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch' }
        - { src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas' }
        - { src: 'INTRA/7', dst: 'INTRA/7' }
        - { src: 'BATCH/7', dst: 'BATCH/7' }
        - { src: 'SPCONTAS/7', dst: 'SPCONTAS/7' }
    ################################################################################## Realiza a desmontagem