- hosts: 
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  become: true
  tasks:
    ################################################################################## Realiza a montagem
    - name: Montar partição INTRA - Terça
      mount:
        src: 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - { src: 'INTRA/2', dst: 'INTRA/2' }
        - { src: 'BATCH/2', dst: 'BATCH/2' }
        - { src: 'SPCONTAS/2', dst: 'SPCONTAS/2' }
    ################################################################################## Realiza a montagem

    ################################################################################## Realiza a montagem
    - name: Montar partição INTRA - Terça
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - { src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra' }
        - { src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch' }
        - { src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas' }
    ################################################################################## Realiza a montagem
    
    ################################################################################## Realiza a copia dos arquivos
    - name: Copiando arquivos
      copy:
        src:
        dest:
      become: true
      loop:
        - { src: '/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/INTRA/2/*', dst: '/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/intra/' }
        - { src: '/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/BATCH/2/*', dst: '/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/batch/' }
        - { src: '/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/SPCONTAS/2/*', dst: '/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/bd/spcontas/' }
    ################################################################################## Realiza a copia dos arquivos

    ################################################################################## Realiza a desmontagem
      mount:
        path: /mnt/{{ item.dst }}
        state: absent
      become: true
      loop:
        - { src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra' }
        - { src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch' }
        - { src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas' }
        - { src: 'INTRA/2', dst: 'INTRA/2' }
        - { src: 'BATCH/2', dst: 'BATCH/2' }
        - { src: 'SPCONTAS/2', dst: 'SPCONTAS/2' }
    ################################################################################## Realiza a desmontagem