# ######################################################
# Backup do GITLAB e NEXUS  Semanal  -  Sempre ás 23h  #
# ######################################################     

# Objetivo: copiar sempre o ultimo arquivo(7=Domingo), nesse caso sempre aos Domingo ás 22h. Atenção sempre mantém 7 dias e depois sobreescrever no 8 dia.

# Passos do Playbook


# 1) Montar - nas3.dpe-go.intra:/backup/iris3/backup_gitlab e nas3.dpe-go.intra:/backup/iris3/backup_nexus
# 2) Montar - nas3.dpe-go.intra:/backup/iris3/backup_gitlab e nas3.dpe-go.intra:/backup/iris3/backup_nexus
# 3) Copiar arquivos comparando, exemplo diff - (Origem - nas3.dpe-go.intra) para Destino (Destino - nas3.dpe-go.intra)
# 4) Desmontar origem (Origem - nas3.dpe-go.intra) e Destino ( Destino - nas3.dpe-go.intra)


# nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/nexus/dom    nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/nexus/dom
# nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/git/dom      nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/git/dom 

- hosts: backup
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  become: true
  tasks:
    ################################################################################## Realiza a montagem
    - name: Montar partição 
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/{{ item }}/dom
        path: /mnt/origem-{{ item }}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - nexus
        - git

    ################################################################################## Realiza a montagem

    ################################################################################## Realiza a montagem
    - name: Montar partição 
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-devops/{{ item }}/dom
        path: /mnt/destino-{{ item }}
        opts: ro
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - nexus
        - git

    ################################################################################## Realiza a montagem
    
    ################################################################################## Realizando DIFF
    - name: Executar diff
      command: diff /mnt/origem-nexus/ /mnt/destino-nexus/
      register: diff_result_nexus
      ignore_errors: true

    - name: Executar diff
      command: diff /mnt/origem-git/ /mnt/destino-git/
      register: diff_result_git
      ignore_errors: true
    ################################################################################## Realizando DIFF

    ################################################################################## Copiando alterações
    - name: Copiando arquivos
      copy:
        src: /mnt/origem-git/
        dest: /mnt/destino-git/
      become: true
      when: diff_result_git.stdout != ""

    - name: Copiando arquivos
      copy:
        src: /mnt/origem-nexus/
        dest: /mnt/destino-nexus/
      become: true
      when: diff_result_nexus.stdout != ""
    ################################################################################## Copiando alterações

    ################################################################################## Realiza a desmontagem
      mount:
        path: /mnt/{{ item.dst }}
        state: absent
      become: true
      loop:
        - /mnt/origem-git/
        - /mnt/origem-nexus/
        - /mnt/destino-git/
        - /mnt/destino-nexus/
    ################################################################################## Realiza a desmontagem