---

- hosts: backup
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: Montar partição
      mount:
        src: 10.6.45.202:/backup2/FILESERVER/SRV_CLIO30A/moodledata/
        path: /mnt/origem/
        opts: rw
        fstype: nfs
        state: ephemeral
      become: true

    - name: Montar partição
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/diario/ava-prod-public/arquivos/diferencial/{{ item }}
        path: /mnt/{{ item }}
        opts: rw
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - seg
        - ter
        - qua
        - qui
        - sex
        - sab

    - name: Copiar arquivos de forma diferencial com rsync
      synchronize:
        src: /mnt/origem
        dest: /mnt/seg/
        recursive: yes
        delete: yes

    - name: Copiar arquivos de forma diferencial com rsync
      synchronize:
        src: /mnt/origem
        dest: /mnt/ter/
        recursive: yes
        delete: yes

    - name: Copiar arquivos de forma diferencial com rsync
      synchronize:
        src: /mnt/origem
        dest: /mnt/qua/
        recursive: yes
        delete: yes

    - name: Copiar arquivos de forma diferencial com rsync
      synchronize:
        src: /mnt/origem
        dest: /mnt/qui/
        recursive: yes
        delete: yes

    - name: Copiar arquivos de forma diferencial com rsync
      synchronize:
        src: /mnt/origem
        dest: /mnt/sex/
        recursive: yes
        delete: yes

    - name: Copiar arquivos de forma diferencial com rsync
      synchronize:
        src: /mnt/origem
        dest: /mnt/sab/
        recursive: yes
        delete: yes

    - mount:
        path: /mnt/{{ item.dst }}
        state: unmounted
      loop:
        - /mnt/origem
        - /mnt/seg
        - /mnt/ter
        - /mnt/qua
        - /mnt/qui
        - /mnt/sex
        - /mnt/sab
