---

- hosts: backup
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
    - name: Montar partição
      mount:
        src: 10.6.45.202:/backup2/FILESERVER/SRV_CLIO30A/
        path: /mnt/origem
        opts: ro
        fstype: nfs
        state: ephemeral

    - name: Montar partição
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/semanal/ava-prod-public/arquivos/completo/
        path: /mnt/destino
        opts: ro
        fstype: nfs
        state: ephemeral

    - name: Copiando arquivos
      copy:
        src: /mnt/origem/
        dest: /mnt/destino
        remote_src: true

    - mount:
        path: /mnt/{{ item.dst }}
        state: unmounted
      loop:
        - /mnt/origem/
        - /mnt/destino/
