---

- hosts: backup
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
    - name: Montar partição INTRA
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/diario/prod-intra/arquivos/diferencial/dom
        path: /mnt/origem
        opts: ro
        fstype: nfs
        state: ephemeral

    - name: Montar partição INTRA
      mount:
        src: nas3.dpe-go.intra:/semanal/prod-intra/arquivos/completo
        path: /mnt/destino
        opts: ro
        fstype: nfs
        state: ephemeral

    - name: Executar diff Segunda
      command: diff /mnt/origem/ /mnt/destino/
      register: diff_result
      ignore_errors: true

    - name: Copiando arquivos PERSEFONE3_STI
      copy:
        src: /mnt/origem/
        dest: /mnt/destino
      when: diff_result.stdout != ""

    - mount:
        path: /mnt/{{ item.dst }}
        state: unmounted
      loop:
        - /mnt/origem/
        - /mnt/destino/
