---

- hosts: backup
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: Montar partição INTRA
      mount:
        src: 10.6.45.202:/backup2/FILESERVER/SRV_PERSEFONE3_STI/SRV_PERSEFONE3_STI
        path: /mnt/SRV_PERSEFONE3_STI
        opts: rw
        fstype: nfs
        state: ephemeral
      become: true

    - name: Montar partição INTRA
      mount:
        src: nas3.dpe-go.intra:/DIARIO/{{ item }}
        path: /mnt/{{ item }}
        opts: rw
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - seg
        - ter
        - qua
        - qui
        - sex
        - sab
        - dom

    - name: Executar diff
      command: diff /mnt/SRV_PERSEFONE3_STI/ /mnt/{{ item }}/
      register: diff_result
      ignore_errors: true
      loop:
        - seg
        - ter
        - qua
        - qui
        - sex
        - sab

      vars:
        diff_result_seg: "{{ diff_result.results[0] }}"
        diff_result_ter: "{{ diff_result.results[1] }}"
        diff_result_qua: "{{ diff_result.results[2] }}"
        diff_result_qui: "{{ diff_result.results[3] }}"
        diff_result_sex: "{{ diff_result.results[4] }}"
        diff_result_sab: "{{ diff_result.results[5] }}"

    - name: Copiar arquivos PERSEFONE3_STI
      copy:
        src: /mnt/SRV_PERSEFONE3_STI/
        dest: "/mnt/{{ item }}"
      loop:
        - seg
        - ter
        - qua
        - qui
        - sex
        - sab
      when: vars['diff_result_'+item].stdout != ""

    - mount:
        path: /mnt/{{ item.dst }}
        state: unmounted
      loop:
        - /mnt/SRV_PERSEFONE3_STI/
        - /mnt/seg
        - /mnt/ter
        - /mnt/qua
        - /mnt/qui
        - /mnt/sex
        - /mnt/sab
