---

- hosts: backup
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
    - name: Montar partição INTRA - Quinta
      mount:
        src: 10.6.45.202:/backup1/SGBD/SRV_CRONOS3A_STI/data/diario/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: rw
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - {src: 'INTRA/4', dst: 'INTRA/4'}
        - {src: 'BATCH/4', dst: 'BATCH/4'}
        - {src: 'SPCONTAS/4', dst: 'SPCONTAS/4'}

    - name: Montar partição INTRA - Quinta
      mount:
        src: nas3.dpe-go.intra:/diario/{{item.src}}
        path: /mnt/{{item.dst}}
        opts: rw
        fstype: nfs
        state: ephemeral
      become: true
      loop:
        - {src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra'}
        - {src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch'}
        - {src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas'}

    - name: Pegando último arquivo da pasta INTRA
      shell: ls -t /mnt/INTRA/4/ | head -1
      become: true
      register: arquivo_atual_intra

    - name: Pegando último arquivo da pasta BATCH
      shell: ls -t /mnt/BATCH/4/ | head -1
      become: true
      register: arquivo_atual_batch

    - name: Pegando último arquivo da pasta SPCONTAS
      shell: ls -t/mnt/SPCONTAS/4/ | head -1
      become: true
      register: arquivo_atual_spcontas

    - name: Copiando arquivos INTRA
      copy:
        src: /mnt/INTRA/4/{{ arquivo_atual_intra.stdout }}
        dest: "/mnt/prod-intra/bd/intra"
        remote_src: true
      become: true

    - name: Copiando arquivos INTRA
      copy:
        src: /mnt/BATCH/4/{{ arquivo_atual_batch.stdout }}
        dest: "/mnt/prod-intra/bd/batch"
        remote_src: true
      become: true

    - name: Copiando arquivos
      copy:
        src: /mnt/SPCONTAS/4/{{ arquivo_atual_spcontas.stdout }}
        dest: "/mnt/prod-intra/bd/spcontas"
        remote_src: true
      become: true

    - shell: ls -t /mnt/prod-intra/bd/intra/ | tail -1
      register: ultimo_arquivo_intra

    - shell: ls -t /mnt/prod-intra/bd/batch/ | tail -1
      register: ultimo_arquivo_batch

    - shell: ls -t /mnt/prod-intra/bd/spcontas/ | tail -1
      register: ultimo_arquivo_spcontas

    - name: Remove file (delete file)
      file:
        path: /mnt/prod-intra/bd/intra/{{ ultimo_arquivo_intra }}
        state: absent
      become: true

    - name: Remove file (delete file)
      file:
        path: /mnt/prod-intra/bd/batch/{{ ultimo_arquivo_batch }}
        state: absent
      become: true

    - name: Remove file (delete file)
      file:
        path: /mnt/prod-intra/bd/spcontas/{{ ultimo_arquivo_spcontas }}
        state: absent
      become: true

    - mount:
        path: /mnt/{{ item.dst }}
        state: absent
      become: true
      loop:
        - {src: 'prod-intra/bd/intra', dst: 'prod-intra/bd/intra'}
        - {src: 'prod-intra/bd/batch', dst: 'prod-intra/bd/batch'}
        - {src: 'prod-intra/bd/spcontas', dst: 'prod-intra/bd/spcontas'}
        - {src: 'INTRA/4', dst: 'INTRA/4'}
        - {src: 'BATCH/4', dst: 'BATCH/4'}
        - {src: 'SPCONTAS/4', dst: 'SPCONTAS/4'}
