---

- hosts: backup
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  tasks:
    - name: Montar partição INTRA
      mount:
        src: 10.6.45.202:/backup/prod_intra/horas3a/ELK
        path: /mnt/origem
        opts: rw
        fstype: nfs
        state: ephemeral

    - name: Montar partição
      mount:
        src: nas3.dpe-go.intra:/mnt/STG7A_UDMARISTA/NAS3/DIARIO/prod-intra/elk/completo/
        path: /mnt/destino
        opts: rw
        fstype: nfs
        state: ephemeral

    - name: Executar diff
      command: diff /mnt/origem/ /mnt/destino/
      register: diff_result
      ignore_errors: true

    - name: Copiando arquivoss
      copy:
        src: /mnt/origem/
        dest: /mnt/destino/
      when: diff_result.stdout != ""

      mount:
        path: /mnt/{{ item.dst }}
        state: absent
      loop:
        - /mnt/origem/
        - /mnt/destino/
